### PR TITLE
Jpk/redux location

### PR DESCRIPTION
**Pull request by jpknoll**
More location to a dedicated component, service, and redux dispatch

### CODE REVIEW

**Comment by srkirkland** [comment]
selfie-0
[_GitHub Selfies_](https://github.com/thieman/github-selfies/)

**Comment by jpknoll** [comment]
Some more work is required after we make decisions about what to do if a person doesn't show their location. 

Do we hide the shuttle card, dining card and nearby card?
What do we default for location?

**Comment by i8wu** [comment]
We're open to suggestions on how to handle the cards if location is disabled but check #79 for suggested solutions. 

Also, I'm not sure how useful/necessary a default location is? What do we gain by having the user's location defaulted to the center of campus? (for example)

**Comment by jpknoll** [comment]
For now, I'll add a text filler that asks the user to enable location. When we introduce a card behavior service, we'll hide the cards and instead serve up a single "please enable location for better cards", similar to how google now works.

**Comment by jpknoll** [comment]
This last couple commits prevents the soft ask on every app reload. We ask only if the getPermissionStatus returns undetermined, which means we haven't made a hard ask yet. After that, it won't bother asking again.

**Comment by i8wu** [comment]
Found a couple things
1. On iOS, user is actually prompted twice for location permission because iOS already has a built in prompt when geolocation is used (I believe)
2. Looks like Dining Card stays in alphabetical order even on app restart, instead of distance ordering.
3. Nearby Card seems to use initial seed location of center of campus, this updates about after a second, but the map position doesn’t update to user location.

**Comment by jpknoll** [comment]
1. This is on purpose. If the user hits Decline, you don't get another chance to ask. We can stylize our  soft ask to make it less confusing.
2. I'll give this another look over. The refresh logic on these cards is a bit confusing.
3. I'll have to give the map a look over as well.

**Comment by jpknoll** [comment]
Fixed the sort and map issue. The animation is still a bit wonky, but I'm trying to follow the example set out here: https://github.com/airbnb/react-native-maps/blob/master/example/examples/DisplayLatLng.js

**Pull request merged**
