### PR TITLE
Redux

### PR DESCRIPTION
**Pull request by jpknoll**

### CODE REVIEW

**Comment by srkirkland** [comment]
Notes from @jpknoll (because github is down for him):

you’ll notice that i only elevate/connect() components that need access to the store or dispatch

so using redux doesn’t mean we need to convert our entire codebase, just that you wrap everything in the <Provider> and connect where you want.

the other gotcha between production apps and the guides is your store doesn’t need to perfectly reflect your component hierarchy

**Comment by i8wu** [comment]
Nice work on the redux implementation, only problem I see is redux isn't in package.json.
Also, cool find with the react-native-popup-menu, but it seems like it has broken the HomeView ScrollView. Tested on my Android Phone (API22), iOS sim, iTouch running latest iOS.

Also, another thought...the popup menu (like this one) is more of a android paradigm, should we be opting for a more native solution or style the menu so it would be more iOS looking?

**Comment by jpknoll** [comment]
Redux is pulled in as dependency, so you don't need to list is specifically.

I don't own an iphone, so I'm not familiar with what paradigms exist there, only that the app is modeled after google now :-D

I'll test with the iphone simulator re: scrollview issues.

**Comment by srkirkland** [comment]
@i8wu  The popup menu concept is taken from the iOS Google app which has the google-now style cards.  Not totally in love with the design but it's how Google is doing it so we thought it's be a good place to start.
 
Attached is a screenshot from my iPhone.

image

**Comment by jpknoll** [comment]
@i8wu resolved the scrollview issue

**Comment by i8wu** [comment]
I think iOS apps are supposed to use something like this according to iOS.

image

But it may be fine to have it that other way since it's how Google has it. Facebook also doesn't follow iOS guidelines and does a sort of in between 

14807951_10211489210773911_388076953_o

(I also have an android and am fine with the look of Google's submenu though, ha)

**Comment by i8wu** [comment]
@jpknoll I think we're gonna wait for some input from our UI specialist Jeremy before using the menu module. Would you mind taking it out for this pull request and we can focus a bit more on the redux? Thanks.

**Comment by c3bryant** [comment]
@jpknoll can you please remove any caret/tilde's from package.json dependencies added? It may be fine in this case but we would like to stick with just static dependency versioning going forward due to issues that have come up a few times recently

**Comment by woznaut** [comment]
while I agree with @i8wu that that's the correct style for an iOS native popup I think @srkirkland has the right approach. We already headed down this card-based path and I think this approach will ultimately be much more in line with what we need.

**Pull request merged**
